import { Interaction, TypedOutcomeBundle } from '@elrondnetwork/erdjs/out';
import { FarmState } from 'src/models/staking/farm.state';
import { StakeGoldElrondProxyService } from '../../elrond-communication/elrond-proxy.service';
import { SmartContractProfiler } from '../../utils/smartcontract.profiler';
export declare class AbiStakingService {
    private readonly elrondProxy;
    private readonly logger;
    private readonly resultParser;
    constructor(elrondProxy: StakeGoldElrondProxyService);
    getGenericData(contract: SmartContractProfiler, interaction: Interaction): Promise<TypedOutcomeBundle>;
    calculateRewardsForGivenPosition(farmAddress: string, amount: string, attributes: string): Promise<string>;
    getContractState(farmAddress: string): Promise<string>;
    getFarmTokenSupply(farmAddress: string): Promise<string>;
    getAnnualPercentageRewards(farmAddress: string): Promise<string>;
    getPerBlockRewardAmount(farmAddress: string): Promise<string>;
    getLastRewardBlockNonce(farmAddress: string): Promise<string>;
    getUndistributedFees(farmAddress: string): Promise<string>;
    getCurrentBlockFee(farmAddress: string): Promise<string>;
    getRewardsPerBlock(farmAddress: string): Promise<string>;
    getDivisionSafetyConstant(farmAddress: string): Promise<string>;
    getProduceRewardsEnabled(farmAddress: string): Promise<boolean>;
    getRewardPerShare(farmAddress: string): Promise<string>;
    getRewardsLeft(farmAddress: string): Promise<string>;
    getGroupIdentifiers(): Promise<string[]>;
    getAddressesByGroupId(groupId: string): Promise<string[]>;
    getGroupByOwner(address: string): Promise<string | undefined>;
    getVestingAddressByGroupIdentifier(groupId: string): Promise<string>;
    getLockedAssetTokenId(vestingAddress: string): Promise<string>;
    getFarmTokenId(childContractAddress: string): Promise<string>;
    getFarmingTokenId(childContractAddress: string): Promise<string>;
    getRewardTokenId(childContractAddress: string): Promise<string>;
    getRewardTokenIdByGroupId(groupId: string): Promise<string>;
    areRewardsLocked(childContractAddress: string): Promise<boolean>;
    getVestingScAddress(farmAddress: string): Promise<string | undefined>;
    getFarmState(address: string): Promise<FarmState>;
}
