import BigNumber from 'bignumber.js';
import { AbiStakingService } from './staking.abi.service';
import { StakeGoldProxyService } from '../../proxy/proxy.service';
import { StakeGoldElrondApiService } from 'src/endpoints/elrond-communication/elrond-api.service';
import { EsdtToken, FarmState, NftCollection } from 'src/models';
import { FarmStakingGroupContract } from 'src/models/staking/farm.staking.contract';
export declare class StakingGetterService {
    private readonly abiService;
    private readonly elrondApiService;
    private readonly proxyService;
    private readonly logger;
    constructor(abiService: AbiStakingService, elrondApiService: StakeGoldElrondApiService, proxyService: StakeGoldProxyService);
    private getData;
    calculateRewardsForGivenPosition(farmAddress: string, amount: string, attributes: string): Promise<BigNumber>;
    getContractState(farmAddress: string): Promise<string>;
    getFarmTokenSupply(farmAddress: string): Promise<string>;
    getAnnualPercentageRewards(farmAddress: string): Promise<string>;
    getCurrentEpoch(): Promise<number>;
    getPerBlockRewardAmount(farmAddress: string): Promise<string>;
    getShardCurrentBlockNonce(shardID: number): Promise<number>;
    getLastRewardBlockNonce(farmAddress: string): Promise<number>;
    getRewardsPerBlock(farmAddress: string): Promise<string>;
    getUndistributedFees(farmAddress: string): Promise<string>;
    getCurrentBlockFee(farmAddress: string): Promise<string>;
    getDivisionSafetyConstant(farmAddress: string): Promise<string>;
    getProduceRewardsEnabled(farmAddress: string): Promise<boolean>;
    getRewardPerShare(farmAddress: string): Promise<string>;
    getRewardsLeft(farmAddress: string): Promise<string>;
    getGroupIdentifiers(): Promise<string[]>;
    getAddressesByGroupId(groupId: string): Promise<string[]>;
    getFarmTokenId(childContractAddress: string): Promise<string>;
    getFarmingTokenId(childContractAddress: string): Promise<string>;
    getRewardTokenId(childContractAddress: string): Promise<string>;
    areRewardsLocked(childContractAddress: string): Promise<boolean>;
    getVestingAddressByGroupIdentifier(groupId: string): Promise<string | undefined>;
    getVestingAdressOfFarm(farmAddress: string): Promise<string>;
    getGroupByOwner(address: string): Promise<string | undefined>;
    getFarmState(address: string): Promise<FarmState>;
    getEsdtOrNft(identifier: string): Promise<EsdtToken | NftCollection | undefined>;
    getLockedAssetTokenId(groupId: string): Promise<string | undefined>;
    getFarmStakingGroups(): Promise<FarmStakingGroupContract[]>;
}
